-- ═══════════════════════════════════════════════════════════════════════════
-- FamilyHub – Supabase / PostgreSQL schema
-- Run this entire file in the Supabase SQL Editor (once).
-- ═══════════════════════════════════════════════════════════════════════════

-- Helper: grant full access to anon role (no auth required for this app)
-- We'll apply this after every table.

-- ─── USERS ────────────────────────────────────────────────────────────────────

create table if not exists users (
  id   bigint generated by default as identity primary key,
  name text not null
);
alter table users disable row level security;
grant all on users to anon, authenticated;

-- ─── TASK CATEGORIES ─────────────────────────────────────────────────────────

create table if not exists task_categories (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_at timestamptz default now()
);
alter table task_categories disable row level security;
grant all on task_categories to anon, authenticated;

-- ─── TASKS ───────────────────────────────────────────────────────────────────

create table if not exists tasks (
  id                  bigint generated by default as identity primary key,
  title               text not null,
  description         text,
  category            text default 'Home',
  priority            text default 'Medium',
  recurrence_type     text default 'One-time',
  recurrence_unit     text,
  recurrence_interval integer,
  recurrence_months   text,
  recurrence_days     text,
  recurrence_anchor   text,
  is_active           boolean default true,
  photo_path          text,
  created_at          timestamptz default now()
);
alter table tasks disable row level security;
grant all on tasks to anon, authenticated;

create table if not exists task_completions (
  id           bigint generated by default as identity primary key,
  task_id      bigint not null references tasks(id) on delete cascade,
  completed_at timestamptz default now(),
  completed_by bigint references users(id),
  notes        text,
  photo_path   text
);
alter table task_completions disable row level security;
grant all on task_completions to anon, authenticated;

create table if not exists task_requirements (
  id          bigint generated by default as identity primary key,
  task_id     bigint not null references tasks(id) on delete cascade,
  description text not null,
  is_done     boolean default false,
  sort_order  integer default 0
);
alter table task_requirements disable row level security;
grant all on task_requirements to anon, authenticated;

-- ─── MEALS ───────────────────────────────────────────────────────────────────

create table if not exists meals (
  id                 bigint generated by default as identity primary key,
  name               text not null,
  description        text,
  photo_path         text,
  category           text,
  recipe             text,
  min_frequency_days integer default 0,
  created_at         timestamptz default now()
);
alter table meals disable row level security;
grant all on meals to anon, authenticated;

create table if not exists meal_ingredients (
  id         bigint generated by default as identity primary key,
  meal_id    bigint not null references meals(id) on delete cascade,
  name       text not null,
  quantity   text,
  unit       text,
  sort_order integer default 0
);
alter table meal_ingredients disable row level security;
grant all on meal_ingredients to anon, authenticated;

create table if not exists meal_ratings (
  id       bigint generated by default as identity primary key,
  meal_id  bigint not null references meals(id) on delete cascade,
  user_id  bigint not null references users(id),
  rating   integer not null,
  rated_at timestamptz default now(),
  unique (meal_id, user_id)
);
alter table meal_ratings disable row level security;
grant all on meal_ratings to anon, authenticated;

create table if not exists meal_history (
  id      bigint generated by default as identity primary key,
  meal_id bigint not null references meals(id) on delete cascade,
  made_at timestamptz default now(),
  notes   text
);
alter table meal_history disable row level security;
grant all on meal_history to anon, authenticated;

create table if not exists meals_to_try (
  id               bigint generated by default as identity primary key,
  name             text not null,
  description      text,
  photo_path       text,
  proposed_by      bigint references users(id),
  proposed_at      timestamptz default now(),
  promoted_meal_id bigint references meals(id)
);
alter table meals_to_try disable row level security;
grant all on meals_to_try to anon, authenticated;

create table if not exists meal_try_votes (
  id          bigint generated by default as identity primary key,
  meal_try_id bigint not null references meals_to_try(id) on delete cascade,
  user_id     bigint not null references users(id),
  vote        text not null,
  voted_at    timestamptz default now(),
  unique (meal_try_id, user_id)
);
alter table meal_try_votes disable row level security;
grant all on meal_try_votes to anon, authenticated;

create table if not exists restaurants (
  id         bigint generated by default as identity primary key,
  name       text not null,
  cuisine    text,
  dine_in    boolean default true,
  takeout    boolean default true,
  notes      text,
  created_at timestamptz default now()
);
alter table restaurants disable row level security;
grant all on restaurants to anon, authenticated;

create table if not exists restaurant_ratings (
  id            bigint generated by default as identity primary key,
  restaurant_id bigint not null references restaurants(id) on delete cascade,
  user_id       bigint not null references users(id),
  rating        integer not null,
  rated_at      timestamptz default now(),
  unique (restaurant_id, user_id)
);
alter table restaurant_ratings disable row level security;
grant all on restaurant_ratings to anon, authenticated;

create table if not exists restaurant_visits (
  id            bigint generated by default as identity primary key,
  restaurant_id bigint not null references restaurants(id) on delete cascade,
  visited_at    timestamptz default now(),
  visit_type    text,
  notes         text
);
alter table restaurant_visits disable row level security;
grant all on restaurant_visits to anon, authenticated;

create table if not exists restaurant_visit_items (
  id         bigint generated by default as identity primary key,
  visit_id   bigint not null references restaurant_visits(id) on delete cascade,
  item_name  text not null,
  rating     integer,
  photo_path text,
  notes      text
);
alter table restaurant_visit_items disable row level security;
grant all on restaurant_visit_items to anon, authenticated;

create table if not exists meal_plan_slots (
  id             bigint generated by default as identity primary key,
  week_start     text not null,
  day_of_week    integer not null,
  meal_type      text not null,
  slot_type      text default 'empty',
  meal_id        bigint references meals(id),
  restaurant_id  bigint references restaurants(id),
  leftovers_note text,
  cook_id        bigint references users(id),
  reminder_time  text,
  unique (week_start, day_of_week, meal_type)
);
alter table meal_plan_slots disable row level security;
grant all on meal_plan_slots to anon, authenticated;

create table if not exists meal_plan_slot_attendees (
  id      bigint generated by default as identity primary key,
  slot_id bigint not null references meal_plan_slots(id) on delete cascade,
  user_id bigint not null references users(id),
  unique (slot_id, user_id)
);
alter table meal_plan_slot_attendees disable row level security;
grant all on meal_plan_slot_attendees to anon, authenticated;

-- ─── SHOPPING ────────────────────────────────────────────────────────────────

create table if not exists shopping_lists (
  id           bigint generated by default as identity primary key,
  name         text not null,
  store_name   text,
  created_by   bigint references users(id),
  created_at   timestamptz default now(),
  completed_at timestamptz,
  is_archived  boolean default false,
  is_template  boolean default false,
  template_id  bigint references shopping_lists(id)
);
alter table shopping_lists disable row level security;
grant all on shopping_lists to anon, authenticated;

create table if not exists shopping_items (
  id           bigint generated by default as identity primary key,
  list_id      bigint not null references shopping_lists(id) on delete cascade,
  name         text not null,
  quantity     numeric default 1,
  unit         text,
  description  text,
  notes        text,
  photo_path   text,
  is_checked   boolean default false,
  is_recurring boolean default false,
  added_by     bigint references users(id),
  added_at     timestamptz default now(),
  checked_by   bigint references users(id),
  checked_at   timestamptz
);
alter table shopping_items disable row level security;
grant all on shopping_items to anon, authenticated;

create table if not exists store_item_library (
  id               bigint generated by default as identity primary key,
  store_name       text not null,
  item_name        text not null,
  default_quantity numeric default 1,
  default_unit     text,
  notes            text
);
alter table store_item_library disable row level security;
grant all on store_item_library to anon, authenticated;

create table if not exists purchase_records (
  id           bigint generated by default as identity primary key,
  list_id      bigint references shopping_lists(id),
  store_name   text,
  notes        text,
  purchased_at timestamptz default now()
);
alter table purchase_records disable row level security;
grant all on purchase_records to anon, authenticated;

create table if not exists purchase_record_items (
  id           bigint generated by default as identity primary key,
  purchase_id  bigint not null references purchase_records(id) on delete cascade,
  name         text not null,
  quantity     numeric,
  unit         text,
  is_recurring boolean default false
);
alter table purchase_record_items disable row level security;
grant all on purchase_record_items to anon, authenticated;

-- ─── PURCHASES (expense tracker) ─────────────────────────────────────────────

create table if not exists purchases (
  id           bigint generated by default as identity primary key,
  store        text,
  purchased_at timestamptz default now(),
  notes        text,
  created_by   bigint references users(id)
);
alter table purchases disable row level security;
grant all on purchases to anon, authenticated;

create table if not exists purchase_items (
  id          bigint generated by default as identity primary key,
  purchase_id bigint not null references purchases(id) on delete cascade,
  name        text not null,
  quantity    numeric default 1,
  unit_price  numeric,
  photo_path  text,
  notes       text
);
alter table purchase_items disable row level security;
grant all on purchase_items to anon, authenticated;

-- ─── INVENTORY ───────────────────────────────────────────────────────────────

create table if not exists inventory_items (
  id               bigint generated by default as identity primary key,
  name             text not null,
  description      text,
  category         text,
  location         text,
  quantity         numeric default 1,
  unit             text,
  best_before_date text,
  purchase_date    text,
  purchase_price   numeric,
  store            text,
  serial_number    text,
  model_number     text,
  estimated_value  numeric,
  notes            text,
  status           text default 'active',
  removed_at       timestamptz,
  removal_notes    text,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);
alter table inventory_items disable row level security;
grant all on inventory_items to anon, authenticated;

create table if not exists inventory_photos (
  id         bigint generated by default as identity primary key,
  item_id    bigint not null references inventory_items(id) on delete cascade,
  photo_path text not null,
  sort_order integer default 1
);
alter table inventory_photos disable row level security;
grant all on inventory_photos to anon, authenticated;

-- ─── CITIES & ADVENTURES ─────────────────────────────────────────────────────

create table if not exists cities (
  id       bigint generated by default as identity primary key,
  name     text not null,
  province text,
  country  text default 'Canada'
);
alter table cities disable row level security;
grant all on cities to anon, authenticated;

create table if not exists friends (
  id         bigint generated by default as identity primary key,
  first_name text not null,
  last_name  text,
  email      text,
  created_at timestamptz default now()
);
alter table friends disable row level security;
grant all on friends to anon, authenticated;

create table if not exists escape_room_venues (
  id      bigint generated by default as identity primary key,
  name    text not null,
  city_id bigint not null references cities(id),
  address text,
  website text,
  notes   text
);
alter table escape_room_venues disable row level security;
grant all on escape_room_venues to anon, authenticated;

create table if not exists escape_rooms (
  id               bigint generated by default as identity primary key,
  venue_id         bigint not null references escape_room_venues(id) on delete cascade,
  name             text not null,
  min_participants integer,
  max_participants integer,
  difficulty       text,
  description      text,
  is_active        boolean default true
);
alter table escape_rooms disable row level security;
grant all on escape_rooms to anon, authenticated;

create table if not exists escape_room_completions (
  id              bigint generated by default as identity primary key,
  room_id         bigint not null references escape_rooms(id) on delete cascade,
  played_at       text,
  escaped         integer,
  time_taken_mins integer,
  rating          integer,
  notes           text,
  created_at      timestamptz default now()
);
alter table escape_room_completions disable row level security;
grant all on escape_room_completions to anon, authenticated;

create table if not exists escape_room_completion_users (
  completion_id bigint not null references escape_room_completions(id) on delete cascade,
  user_id       bigint not null references users(id),
  primary key (completion_id, user_id)
);
alter table escape_room_completion_users disable row level security;
grant all on escape_room_completion_users to anon, authenticated;

create table if not exists escape_room_completion_friends (
  completion_id bigint not null references escape_room_completions(id) on delete cascade,
  friend_id     bigint not null references friends(id),
  primary key (completion_id, friend_id)
);
alter table escape_room_completion_friends disable row level security;
grant all on escape_room_completion_friends to anon, authenticated;

create table if not exists escape_room_completion_ratings (
  completion_id bigint not null references escape_room_completions(id) on delete cascade,
  user_id       bigint not null references users(id),
  rating        integer not null,
  primary key (completion_id, user_id)
);
alter table escape_room_completion_ratings disable row level security;
grant all on escape_room_completion_ratings to anon, authenticated;

create table if not exists user_preferences (
  user_id         bigint primary key references users(id),
  default_city_id bigint references cities(id)
);
alter table user_preferences disable row level security;
grant all on user_preferences to anon, authenticated;

-- ─── MINI GOLF ───────────────────────────────────────────────────────────────

create table if not exists mini_golf_venues (
  id      bigint generated by default as identity primary key,
  city_id bigint not null references cities(id),
  name    text not null,
  address text,
  website text,
  notes   text
);
alter table mini_golf_venues disable row level security;
grant all on mini_golf_venues to anon, authenticated;

create table if not exists mini_golf_courses (
  id        bigint generated by default as identity primary key,
  venue_id  bigint not null references mini_golf_venues(id) on delete cascade,
  name      text not null,
  holes     integer default 18,
  par       integer,
  notes     text,
  is_active boolean default true
);
alter table mini_golf_courses disable row level security;
grant all on mini_golf_courses to anon, authenticated;

create table if not exists mini_golf_sessions (
  id         bigint generated by default as identity primary key,
  course_id  bigint not null references mini_golf_courses(id) on delete cascade,
  played_at  text,
  notes      text,
  created_at timestamptz default now()
);
alter table mini_golf_sessions disable row level security;
grant all on mini_golf_sessions to anon, authenticated;

create table if not exists mini_golf_session_users (
  session_id bigint not null references mini_golf_sessions(id) on delete cascade,
  user_id    bigint not null references users(id),
  primary key (session_id, user_id)
);
alter table mini_golf_session_users disable row level security;
grant all on mini_golf_session_users to anon, authenticated;

create table if not exists mini_golf_session_friends (
  session_id bigint not null references mini_golf_sessions(id) on delete cascade,
  friend_id  bigint not null references friends(id),
  primary key (session_id, friend_id)
);
alter table mini_golf_session_friends disable row level security;
grant all on mini_golf_session_friends to anon, authenticated;

create table if not exists mini_golf_scores (
  id          bigint generated by default as identity primary key,
  session_id  bigint not null references mini_golf_sessions(id) on delete cascade,
  user_id     bigint not null references users(id),
  total_score integer not null
);
alter table mini_golf_scores disable row level security;
grant all on mini_golf_scores to anon, authenticated;

create table if not exists mini_golf_ratings (
  session_id bigint not null references mini_golf_sessions(id) on delete cascade,
  user_id    bigint not null references users(id),
  rating     integer not null,
  primary key (session_id, user_id)
);
alter table mini_golf_ratings disable row level security;
grant all on mini_golf_ratings to anon, authenticated;

-- ─── BOWLING ─────────────────────────────────────────────────────────────────

create table if not exists bowling_venues (
  id      bigint generated by default as identity primary key,
  city_id bigint not null references cities(id),
  name    text not null,
  address text,
  website text,
  notes   text
);
alter table bowling_venues disable row level security;
grant all on bowling_venues to anon, authenticated;

create table if not exists bowling_sessions (
  id         bigint generated by default as identity primary key,
  venue_id   bigint not null references bowling_venues(id) on delete cascade,
  played_at  text,
  notes      text,
  created_at timestamptz default now()
);
alter table bowling_sessions disable row level security;
grant all on bowling_sessions to anon, authenticated;

create table if not exists bowling_session_users (
  session_id bigint not null references bowling_sessions(id) on delete cascade,
  user_id    bigint not null references users(id),
  primary key (session_id, user_id)
);
alter table bowling_session_users disable row level security;
grant all on bowling_session_users to anon, authenticated;

create table if not exists bowling_session_friends (
  session_id bigint not null references bowling_sessions(id) on delete cascade,
  friend_id  bigint not null references friends(id),
  primary key (session_id, friend_id)
);
alter table bowling_session_friends disable row level security;
grant all on bowling_session_friends to anon, authenticated;

create table if not exists bowling_scores (
  id          bigint generated by default as identity primary key,
  session_id  bigint not null references bowling_sessions(id) on delete cascade,
  user_id     bigint not null references users(id),
  game_number integer not null default 1,
  score       integer not null
);
alter table bowling_scores disable row level security;
grant all on bowling_scores to anon, authenticated;

create table if not exists bowling_ratings (
  session_id bigint not null references bowling_sessions(id) on delete cascade,
  user_id    bigint not null references users(id),
  rating     integer not null,
  primary key (session_id, user_id)
);
alter table bowling_ratings disable row level security;
grant all on bowling_ratings to anon, authenticated;

-- ─── MOVIES ──────────────────────────────────────────────────────────────────

create table if not exists movies (
  id         bigint generated by default as identity primary key,
  title      text not null,
  year       integer,
  genre      text,
  notes      text,
  created_at timestamptz default now()
);
alter table movies disable row level security;
grant all on movies to anon, authenticated;

create table if not exists movie_viewings (
  id           bigint generated by default as identity primary key,
  movie_id     bigint not null references movies(id) on delete cascade,
  viewed_at    text,
  venue_type   text default 'home',
  theater_name text,
  notes        text,
  created_at   timestamptz default now()
);
alter table movie_viewings disable row level security;
grant all on movie_viewings to anon, authenticated;

create table if not exists movie_viewing_users (
  viewing_id bigint not null references movie_viewings(id) on delete cascade,
  user_id    bigint not null references users(id),
  primary key (viewing_id, user_id)
);
alter table movie_viewing_users disable row level security;
grant all on movie_viewing_users to anon, authenticated;

create table if not exists movie_viewing_friends (
  viewing_id bigint not null references movie_viewings(id) on delete cascade,
  friend_id  bigint not null references friends(id),
  primary key (viewing_id, friend_id)
);
alter table movie_viewing_friends disable row level security;
grant all on movie_viewing_friends to anon, authenticated;

create table if not exists movie_viewing_ratings (
  viewing_id bigint not null references movie_viewings(id) on delete cascade,
  user_id    bigint not null references users(id),
  rating     integer not null,
  primary key (viewing_id, user_id)
);
alter table movie_viewing_ratings disable row level security;
grant all on movie_viewing_ratings to anon, authenticated;

-- ─── SEQUENCES: allow identity override during migration ──────────────────────
-- (generated by default already allows this — no extra step needed)

-- ─── RPC: filter escape rooms ─────────────────────────────────────────────────

create or replace function filter_escape_rooms(
  p_city_id    bigint,
  p_user_ids   bigint[],
  p_friend_ids bigint[],
  p_mode       text   -- 'new' or 'completed'
)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_result jsonb;
begin
  select jsonb_agg(venue_row order by venue_row->>'name')
  into v_result
  from (
    select jsonb_build_object(
      'id',    v.id,
      'name',  v.name,
      'rooms', (
        select jsonb_agg(room_row order by room_row->>'name')
        from (
          select jsonb_build_object(
            'id',               r.id,
            'name',             r.name,
            'difficulty',       r.difficulty,
            'min_participants', r.min_participants,
            'max_participants', r.max_participants,
            'total_completions', (
              select count(*) from escape_room_completions c where c.room_id = r.id
            ),
            'last_played_at', (
              select max(c.played_at) from escape_room_completions c where c.room_id = r.id
            ),
            'last_escaped', (
              select c.escaped from escape_room_completions c
              where c.room_id = r.id order by c.played_at desc nulls last limit 1
            )
          ) as room_row
          from escape_rooms r
          where r.venue_id = v.id
            and r.is_active = true
            and (
              case when p_mode = 'completed' then (
                -- at least one completion where ALL selected people participated
                exists (
                  select 1 from escape_room_completions c
                  where c.room_id = r.id
                    and (
                      array_length(p_user_ids, 1) is null or
                      not exists (
                        select unnest(p_user_ids) except
                        select ercu.user_id from escape_room_completion_users ercu where ercu.completion_id = c.id
                      )
                    )
                    and (
                      array_length(p_friend_ids, 1) is null or
                      not exists (
                        select unnest(p_friend_ids) except
                        select ercf.friend_id from escape_room_completion_friends ercf where ercf.completion_id = c.id
                      )
                    )
                )
              ) else (
                -- no completion where any selected person participated
                not exists (
                  select 1 from escape_room_completions c
                  where c.room_id = r.id
                    and (
                      (array_length(p_user_ids, 1) is not null and
                       exists (select 1 from escape_room_completion_users ercu where ercu.completion_id = c.id and ercu.user_id = any(p_user_ids)))
                      or
                      (array_length(p_friend_ids, 1) is not null and
                       exists (select 1 from escape_room_completion_friends ercf where ercf.completion_id = c.id and ercf.friend_id = any(p_friend_ids)))
                    )
                )
              ) end
            )
        ) sub
      )
    ) as venue_row
    from escape_room_venues v
    where v.city_id = p_city_id
  ) venues;

  return coalesce(v_result, '[]'::jsonb);
end;
$$;

grant execute on function filter_escape_rooms to anon, authenticated;

-- ─── RPC: upsert meal rating ──────────────────────────────────────────────────

create or replace function upsert_meal_rating(
  p_meal_id bigint,
  p_user_id bigint,
  p_rating  integer
)
returns void language plpgsql security definer as $$
begin
  insert into meal_ratings (meal_id, user_id, rating)
  values (p_meal_id, p_user_id, p_rating)
  on conflict (meal_id, user_id) do update set rating = p_rating, rated_at = now();
end;
$$;
grant execute on function upsert_meal_rating to anon, authenticated;

-- ─── RPC: upsert restaurant rating ───────────────────────────────────────────

create or replace function upsert_restaurant_rating(
  p_restaurant_id bigint,
  p_user_id       bigint,
  p_rating        integer
)
returns void language plpgsql security definer as $$
begin
  insert into restaurant_ratings (restaurant_id, user_id, rating)
  values (p_restaurant_id, p_user_id, p_rating)
  on conflict (restaurant_id, user_id) do update set rating = p_rating, rated_at = now();
end;
$$;
grant execute on function upsert_restaurant_rating to anon, authenticated;

-- ─── RPC: upsert meal try vote ────────────────────────────────────────────────

create or replace function upsert_meal_try_vote(
  p_meal_try_id bigint,
  p_user_id     bigint,
  p_vote        text
)
returns void language plpgsql security definer as $$
begin
  insert into meal_try_votes (meal_try_id, user_id, vote)
  values (p_meal_try_id, p_user_id, p_vote)
  on conflict (meal_try_id, user_id) do update set vote = p_vote, voted_at = now();
end;
$$;
grant execute on function upsert_meal_try_vote to anon, authenticated;

-- ─── RPC: record shopping purchase ───────────────────────────────────────────

create or replace function record_shopping_purchase(
  p_list_id       bigint,
  p_purchased_ids bigint[],
  p_carry_back_ids bigint[],
  p_notes         text default null
)
returns bigint language plpgsql security definer as $$
declare
  v_store      text;
  v_purchase_id bigint;
  v_item       record;
begin
  select store_name into v_store from shopping_lists where id = p_list_id;

  insert into purchase_records (list_id, store_name, notes)
  values (p_list_id, v_store, p_notes)
  returning id into v_purchase_id;

  -- Save purchased items to record
  for v_item in
    select * from shopping_items
    where id = any(p_purchased_ids) and list_id = p_list_id
  loop
    insert into purchase_record_items (purchase_id, name, quantity, unit, is_recurring)
    values (v_purchase_id, v_item.name, v_item.quantity, v_item.unit, v_item.is_recurring);

    if v_item.id = any(p_carry_back_ids) then
      -- Uncheck and keep on list
      update shopping_items set is_checked = false, checked_by = null, checked_at = null
      where id = v_item.id;
    else
      -- Remove from list
      delete from shopping_items where id = v_item.id;
    end if;
  end loop;

  return v_purchase_id;
end;
$$;
grant execute on function record_shopping_purchase to anon, authenticated;

-- ─── RPC: new shopping trip from template ────────────────────────────────────

create or replace function new_shopping_trip(p_template_id bigint)
returns bigint language plpgsql security definer as $$
declare
  v_tmpl  record;
  v_name  text;
  v_trip_id bigint;
  v_item  record;
begin
  select * into v_tmpl from shopping_lists where id = p_template_id and is_template = true;
  if not found then raise exception 'Template not found'; end if;

  v_name := v_tmpl.name || ' – ' || to_char(now(), 'Mon DD');
  insert into shopping_lists (name, store_name, created_by, is_template, template_id)
  values (v_name, v_tmpl.store_name, v_tmpl.created_by, false, p_template_id)
  returning id into v_trip_id;

  for v_item in select * from shopping_items where list_id = p_template_id loop
    insert into shopping_items (list_id, name, quantity, unit, description, notes, is_recurring, added_by)
    values (v_trip_id, v_item.name, v_item.quantity, v_item.unit, v_item.description, v_item.notes, v_item.is_recurring, v_item.added_by);
  end loop;

  return v_trip_id;
end;
$$;
grant execute on function new_shopping_trip to anon, authenticated;

-- ─── RPC: upsert meal plan slot ──────────────────────────────────────────────

create or replace function upsert_meal_plan_slot(
  p_week_start     text,
  p_day_of_week    integer,
  p_meal_type      text,
  p_slot_type      text,
  p_meal_id        bigint default null,
  p_restaurant_id  bigint default null,
  p_leftovers_note text   default null,
  p_cook_id        bigint default null,
  p_attendee_ids   bigint[] default null
)
returns bigint language plpgsql security definer as $$
declare
  v_slot_id bigint;
begin
  insert into meal_plan_slots
    (week_start, day_of_week, meal_type, slot_type, meal_id, restaurant_id, leftovers_note, cook_id)
  values
    (p_week_start, p_day_of_week, p_meal_type, p_slot_type, p_meal_id, p_restaurant_id, p_leftovers_note, p_cook_id)
  on conflict (week_start, day_of_week, meal_type) do update set
    slot_type      = excluded.slot_type,
    meal_id        = excluded.meal_id,
    restaurant_id  = excluded.restaurant_id,
    leftovers_note = excluded.leftovers_note,
    cook_id        = excluded.cook_id
  returning id into v_slot_id;

  -- Replace attendees
  delete from meal_plan_slot_attendees where slot_id = v_slot_id;
  if p_attendee_ids is not null then
    insert into meal_plan_slot_attendees (slot_id, user_id)
    select v_slot_id, unnest(p_attendee_ids)
    on conflict do nothing;
  end if;

  return v_slot_id;
end;
$$;
grant execute on function upsert_meal_plan_slot to anon, authenticated;
